version: "3.9"
services:
  mysqldb:
    image: mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'task'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes: 
     - ./dbData:/var/lib/mysql
volumes:
  dbData:
